# .github/workflows/backend-ci.yml
name: Backend CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [ main, master ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/backend
      NASA_API_KEY: "test-key"
      DB_USER: "test"
      DB_PASSWORD: "test"
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  deploy:
    needs: test   # only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Heroku
        run: |
          git subtree split --prefix backend -b backend-deploy
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/solar-impact-api.git backend-deploy:master --force
          git branch -D backend-deploy


